name: Django CI/CD

on:
  push:
    branches:
      - main # Запускать workflow при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Укажите версию Python, которую использует ваш проект

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Настройка базы данных (PostgreSQL)
      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: "14"
          postgresql db: ${{ secrets.POSTGRES_DB }}
          postgresql user: ${{ secrets.POSTGRES_USER }}
          postgresql password: ${{ secrets.POSTGRES_PASSWORD }}

      # 5. Применение миграций
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      # 6. Запуск тестов
      - name: Run tests
        run: |
          python manage.py test

      # 7. Сборка статических файлов
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      # 8. Деплой (опционально)
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /path/to/your/project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          EOF
